schema_version: 1

context:
  version: "0.1.3"

package:
  name: r-anispace
  version: ${{ version }}

source:
  url: https://animovement.r-universe.dev/src/contrib/anispace_${{ version }}.tar.gz
  sha256: dce7b56c9503eeb37fad07411700e16ce1e6d651673b57395b1c4bc0fdea7a29

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --no-multiarch --with-keep.source .

requirements:
  host:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-dplyr
    - r-rlang
  run:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-dplyr
    - r-rlang

tests:
  - script:
      - Rscript -e "library(anispace)"

about:
  homepage: https://github.com/animovement/anispace
  summary: An R package providing spatial transformation methods for movement data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
