schema_version: 1

context:
  version: "0.2.0"
  rev: dd8a6be17188c4da248dcffd732ec2d62d7b9343

package:
  name: r-aniprocess
  version: ${{ version }}

source:
  git: https://github.com/animovement/aniprocess.git
  rev: ${{ rev }}

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --no-multiarch --with-keep.source .

requirements:
  host:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-collapse
    - r-dplyr
    - r-rlang
  run:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-collapse
    - r-dplyr
    - r-rlang

tests:
  - script:
      - Rscript -e "library(aniprocess)"

about:
  homepage: https://github.com/animovement/aniprocess
  summary: An R package for signal processing and filtering of movement data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
