schema_version: 1

context:
  version: "0.1.1"
  rev: eef5c38b89acccc6d855031e1984cdb86dcb7a2f

package:
  name: r-anicheck
  version: ${{ version }}

source:
  git: https://github.com/animovement/anicheck.git
  rev: ${{ rev }}

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --no-multiarch --with-keep.source .

requirements:
  host:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-dplyr
    - r-rlang
  run:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-dplyr
    - r-rlang

tests:
  - script:
      - Rscript -e "library(anicheck)"

about:
  homepage: https://github.com/animovement/anicheck
  summary: An R package for diagnosing movement data quality
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
