schema_version: 1

context:
  version: "0.4.1"
  rev: 457fccf4d43afbcce329f2c55e48ce1a15d10df6

package:
  name: r-aniread
  version: ${{ version }}

source:
  git: https://github.com/animovement/aniread.git
  rev: ${{ rev }}

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --no-multiarch --with-keep.source .

requirements:
  host:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-dplyr
    - r-janitor
    - r-rlang
    - r-stringr
    - r-tidyr
    - r-tidyselect
    - r-vroom
  run:
    - r-base >=4.1.0
    - r-aniframe
    - r-cli
    - r-dplyr
    - r-janitor
    - r-rlang
    - r-stringr
    - r-tidyr
    - r-tidyselect
    - r-vroom

tests:
  - script:
      - Rscript -e "library(aniread)"

about:
  homepage: https://github.com/animovement/aniread
  summary: An R package for reading and writing movement data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
